---
- name: Enable tcp for rsyslog
  blockinfile:
    path: /etc/rsyslog.conf
    block: |
      module(load="imtcp")
      input(type="imtcp" port="514")
  register: remote_rsyslog_added

- name: Suppress joinsplit messages from zend
  copy:
    src: rsyslog_zend.conf
    dest: /etc/rsyslog.d/rsyslog_zend.conf
  register: suppress_zend_rsyslog

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  when: remote_rsyslog_added.changed or suppress_zend_rsyslog.changed